target("platform_ct")
    set_default(false)
    add_files("platform_ct.cpp")
    add_tests("", {build_should_pass = true})
target_end()
target("platform_ct_non128")
    set_default(false)
    add_files("platform_ct_non128.cpp")
    add_tests("", {build_should_pass = true})
target_end()

target("utility_ct")
    set_default(false)
    add_files("utility_ct.cpp")
    add_tests("", {files = "utility_ct.cpp", build_should_pass = true})
target_end()
